### ISSUE TITLE
Using css from github vs your site causes display issues

### ISSUE THREAD

**Issue by benkraj** [jvcasillas/ru_xaringan#1]
Hi Joseph-

I was trying out your rutgers xaringan theme (with the thought to change it to something non-rutgers specific---I hope that's ok), but I've run into some trouble when I use the rutgers.css listed on github vs the one on your personal site.

When the header is listed as here:
```
---
title: "Title here"
subtitle: "Sub-title here"
author: "Your Name"
date: "Rutgers University </br> `r Sys.Date()`"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: ["http://www.jvcasillas.com/ru_xaringan/css/rutgers.css", "http://www.jvcasillas.com/ru_xaringan/css/rutgers-fonts.css"]
    nature:
      beforeInit: "http://www.jvcasillas.com/ru_xaringan/js/ru_xaringan.js"
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: "16:9"
---
```

The code works as expected, but if I point it to seemingly the same rutgers.css file on your github--i.e. changing the css line to:
```
    css: ["https://raw.githubusercontent.com/jvcasillas/ru_xaringan/master/css/rutgers.css", "http://www.jvcasillas.com/ru_xaringan/css/rutgers-fonts.css"]

```  
--- none of the formatting comes through in the presentation.

Am I missing some obvious regarding library files or some other file this is pulling from? My apologies if this is obvious, but I haven't done anything in css.

Any advice you have would be very appreciated, and your theme really looks great--so I certainly complement your work.

Thanks,
Ben
